### PR TITLE
Adding AlphaFold2 Multimer support

### PR DESCRIPTION
**Pull request by narendrachaudhary51**

### CODE REVIEW

**Comment by sanchit-misra** [comment]
Could you remove the commented statements from the docker files and raise a PR to the v3.0 branch?

**Comment by narendrachaudhary51** [comment]
I just did that. Created a new pull request to v3.0-release branch.

________________________________

**Comment by narendrachaudhary51** [comment]
should I delete this pull request?

**Comment by sanchit-misra** [comment]
Yes, delete it

**Pull request closed without merging**
